### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/IBL_root#1]
After following the installation instructions, calling .\pybod.bat returns "no module named pybpodgui_plugin". After calling python -m update.py in the IBL_root pybpod folder, running .pybpod.bat opens the pybpod window successfully.

Also, in pybpod.bat the path indicated as pybpod_dir is not correct on my machine - I installed IBL_root in C:\Users\anne\Documents, instead of C:\. Can the pybpod dir be flexibly set to accommodate this?

**Comment by nbonacchi** [comment]
OK, so the problem is that IBL_root should be "installed" in the C:\ there are a couple of absolute paths in the code that require it to be in that place.
I'll make it more clear in the installation. can you try moving it to C:\IBL_root and reinstall?

**Comment by anne-urai** [comment]
Suggestion: change 
`Checkout this repository in your root folder:
`
to 
`Checkout this repository in your root folder C:\ (do *not* install in another location, since the code has the C:\IBL_root path hardcoded)
`

This would make it clearer that root here refers to the PCs root, not 'any folder that you'd like to be your IBL root'

**Comment by anne-urai** [comment]
I get this error message during the installation (not sure if I can safely ignore it)

conda env create -f environment-windows-10.ymlSolving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.5.2

Please update conda by running

    $ conda update -n base conda



Downloading and Extracting Packages
python 3.5.4: ###################################### | 100%
mkl 2018.0.0: ###################################### | 100%
sip 4.18.1: ######################################## | 100%
libpng 1.6.28: ##################################### | 100%
wheel 0.29.0: ###################################### | 100%
pytz 2017.2: ####################################### | 100%
qscintilla2 2.9.3: ################################# | 100%
pyserial 3.4: ###################################### | 100%
vc 14: ############################################# | 100%
freetype 2.7: ###################################### | 100%
intel-openmp 2018.0.0: ############################# | 100%
sqlite 3.19.3: ##################################### | 100%
ca-certificates 2017.08.26: ######################## | 100%
backports 1.0: ##################################### | 100%
icu 58.2: ########################################## | 100%
certifi 2017.7.27.1: ############################### | 100%
pip 9.0.1: ######################################### | 100%
qt 5.6.2: ########################################## | 100%
numpy 1.13.3: ###################################### | 100%
pyparsing 2.2.0: ################################### | 100%
matplotlib 2.1.0: ################################## | 100%
zlib 1.2.11: ####################################### | 100%
backports.functools_lru_cache 1.4: ################# | 100%
six 1.11.0: ######################################## | 100%
jpeg 9b: ########################################### | 100%
tornado 4.5.2: ##################################### | 100%
cycler 0.10.0: ##################################### | 100%
icc_rt 2017.0.4: ################################### | 100%
setuptools 36.5.0: ################################# | 100%
openssl 1.0.2l: #################################### | 100%
wincertstore 0.2: ################################## | 100%
pyqt 5.6.0: ######################################## | 100%
python-dateutil 2.6.1: ############################# | 100%
vs2015_runtime 14.0.25123: ######################### | 100%
git 2.15.0: ######################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting anyqt==0.0.8 (from -r C:\IBL_root\pybpod\condaenv.5wlxcwl2.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7c/32/f6ae3ad3be05722d344ff8d202d4f0382f7fc75e1ad2fd49cc36ccd2e8a7/AnyQt-0.0.8-py2.py3-none-any.whl
Requirement already satisfied: backports.functools-lru-cache==1.4 in c:\ibl_root\anaconda\envs\pybpod-environment\lib\site-packages (from -r C:\IBL_root\pybpod\condaenv.5wlxcwl2.requirements.txt (line 2))
Collecting send2trash==1.4.2 (from -r C:\IBL_root\pybpod\condaenv.5wlxcwl2.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/6c/de/17f0fd21a9d6565b7bf32e4747486bf13603252451887b93b4346c2d2690/Send2Trash-1.4.2-py3-none-any.whl
Collecting pandas==0.22.0 (from -r C:\IBL_root\pybpod\condaenv.5wlxcwl2.requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/79/39/06ce96c84772460a864a9f6e7c11c98561d8901a9853ffe758c3d2842c68/pandas-0.22.0-cp35-cp35m-win_amd64.whl (9.0MB)
    0% |                                | 30kB 2.0MB/s eta 0:    0% |                                | 40kB 2.6MB/s eta 0:    0% |                                | 51kB 3.3MB/s eta 0:    0% |                                | 61kB 3.9MB/s eta 0:    0% |                                | 71kB 4.6MB/s eta 0:    0% |                                | 81kB 2.6MB/s eta 0:    1% |                                | 92kB 2.8MB/s eta 0:    1% |                                | 102kB 2.9MB/s eta 0    1% |                                | 112kB 2.8MB/s eta 0    1% |                                | 122kB 2.8MB/s eta 0    1% |                                | 133kB 4.4MB/s eta 0    1% |                                | 143kB 4.2MB/s eta 0    1% |                                | 153kB 4.0MB/s eta 0    1% |                                | 163kB 3.9MB/s eta 0    1% |                                | 174kB 3.7MB/s eta 0    2% |                                | 184kB 8.0MB/s eta 0    2% |                                | 194kB 9.3MB/s eta 0    2% |                                | 204kB 9.3MB/s eta 0    2% |                                | 215kB 9.3MB/s eta 0    2% |                                | 225kB 10.2MB/s eta
    2% |                                | 235kB 11.3MB/s eta
    2% |                                | 245kB 12.8MB/s eta
    2% |                                | 256kB 12.8MB/s eta
    2% |                                | 266kB 12.7MB/s eta
    3% |                                | 276kB 12.7MB/s eta
    3% |#                               | 286kB 14.6MB/s eta
    3% |#                               | 296kB 12.7MB/s eta
    3% |#                               | 307kB 16.9MB/s eta
    3% |#                               | 317kB 14.5MB/s eta
    3% |#                               | 327kB 14.5MB/s eta
    3% |#                               | 337kB 14.5MB/s eta
    3% |#                               | 348kB 11.3MB/s eta
Exception:
Traceback (most recent call last):
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\utils\hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\download.py", line 571, in written_chunks
    for chunk in chunks:
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\utils\ui.py", line 141, in iter
    self.next(n)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\_vendor\progress\__init__.py", line 73, in next
    self.update()
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\_vendor\progress\bar.py", line 42, in update
    self.writeln(line)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\_vendor\progress\helpers.py", line 67, in writeln
    self.clearln()
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\_vendor\progress\helpers.py", line 63, in clearln    print('\r\x1b[K', end='', file=self.file)  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 166, in write_and_convert    self.write_plain_text(text, cursor, start)
  File "C:\IBL_root\Anaconda\envs\pybpod-environment\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: raw write() returned invalid length 2 (should have been between 0 and 1)
CondaValueError: pip returned an error
