### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/IBL_root#37]
```
INFO: Configuring pybpod IBL project:


INFO: Done!
You should be good to go...

PS C:\IBL_root> .\pybpod.bat
Finding pybpod folder...
Activating pybpod-environment...
Launching pybpod...
Traceback (most recent call last):
  File "C:\Users\IBL\AppData\Local\Continuum\anaconda3\envs\pybpod-environment\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\IBL\AppData\Local\Continuum\anaconda3\envs\pybpod-environment\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\IBL\AppData\Local\Continuum\anaconda3\envs\pybpod-environment\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "c:\ibl_root\pybpod\pybpod-gui-plugin\pybpodgui_plugin\__init__.py", line 15, in <module>
    from pyforms import conf
  File "c:\ibl_root\pybpod\pyforms\pyforms\__init__.py", line 4, in <module>
    from confapp import conf
ImportError: No module named 'confapp'
done
```

**Comment by nbonacchi** [comment]
That's weird,
The revision of pybpod its pointing to should have downloaded this environment file ([here](https://bitbucket.org/fchampalimaud/pybpod/src/develop/environment-windows-10.yml)) which has confapp marked for installation. Can you check inside the pybpod folder if the env file and the linked file are the same?  At the end of the file you should have something like this:
```
- pip:
  - anyqt==0.0.8
  - backports.functools-lru-cache==1.4
  - send2trash==1.4.2
  - pandas==0.22.0
  - confapp==1.0.0
```
You can manually solve this by installing confapp typing `pip install confapp` after activating pybpod-environment of course.
